[[people]]
name = "Anne Fouilloux"
organization = "UIO University of Oslo, Norway; CR staff"
photo = "anne_fouilloux.jpg"
text = """
Working as a Research Software Engineer at the department of Geosciences.
Software & Data Carpentry instructor.  Carpentry Instructor Trainer.
"""

[[people]]
name = "Bjørn Lindi"
organization = "NTNU; CR staff"
photo = "bjoern_lindi.jpg"
text = """
I used to be a HPC-manager, but I am transforming into a sustainable Research
Software Engineer. My background is in electrical engineering and I have
experience from different software companies. Do also enjoy baking, and make
Ruislimmppu regularly.
"""

[[people]]
name = "Emiliano Molinaro"
organization = "SDU eScience Center; CR staff"
photo = "emiliano_molinaro.jpg"
text = """
Software architect for research infrastructure with a background in Theoretical
Particle Physics. Develops HPC solutions for data science. Working at the
eScience Center, University of Southern Denmark. Enjoys taking long walks in
nature.
"""

[[people]]
name = "Johan Hellsvik"
organization = "PDC Center for High Performance Computing; CR staff"
photo = "johan.jpg"
text = """
Johan is an application expert in materials theory at the PDC Center for High
Performance Computing, KTH, where he is helping users with general scientific
computing problems, code development, optimization and debugging. He has a
passion for Fortran.
"""

[[people]]
name = "Juho Lehtonen"
organization = "CSC - IT center for science; CR staff"
photo = "juho_lehtonen.jpg"
text = """
Working as a software specialist with background in computer science.
Do enjoy orienteering, snowboarding and mushroom picking.
"""

[[people]]
name = "Max R. Eckardt"
organization = "Center for Humanities Computing Aarhus at Aarhus University; CR staff"
photo = "max_eckardt.jpg"
text = """
Working as Research Software Engineer mostly on Full-stack web development.
Holds a PhD in the humanities on explorative search algorithms. Builds a
framework for social software innovation aiming at synergistic collaboration
between programming- and use context experts. Carpentry Instructor.
"""

[[people]]
name = "Naoe Tatara"
organization = "University of Oslo; CR staff"
photo = "naoe.jpg"
text = """
Working as a regional coordinator of CodeRefinery and Carpentries for Nordic
countries, based in Oslo. Having worked for a long time as an interdisciplinary
researcher mainly in the field of design and development of technology for
personal health (eHealth). Always having a high interest in interaction between
human and technology, user experience, and universal design of ICT.
"""

[[people]]
name = "Radovan Bast"
organization = "UiT The Arctic University of Norway; CR staff"
photo = "radovan_bast.jpg"
text = """
Theoretical chemist turned into a computer geek. Working as senior engineer at
the High Performance Computing Group. Enjoys teaching, learning, and discussing
computer languages. Fan of the 8-bit graphics era, loves cooking and
baking and aviation.
"""

[[people]]
name = "Richard Darst"
organization = "Aalto University, Finland"
text = """
HPC and Scientific Computing specialist and Research Software Engineer
with emphasis on training and usability.  Hopes that computing will
never get in the way of anyone's research.
"""

[[people]]
name = "Sabry Razick"
organization = "UIO University of Oslo, Norway; CR staff"
photo = "sabry_razick.jpg"
text = """
Working as a senior engineer at the department of research computing. Holds a
PhD in informatics from University if Oslo.
"""

[[people]]
name = "Samantha Wittke"
organization = "Finnish Geospatial Research Institute, Aalto University, Finland"
photo = "samantha.jpg"
text = """
A geoinformatics/remote sensing researcher who stumbled into the deep end of
the research software engineering pool, now learning to swim with the bigger
fish while also helping others to stay afloat. Enjoys going on adventures
(teaching is one of them!), woodworking and the Finnish language.
"""

[[people]]
name = "Stefan Negru"
organization = "CSC - IT center for science; CR staff"
photo = "stefan_negru.jpg"
text = """
Software Engineer with background in Semantic Web and Human-Computer
Interaction.  Do enjoy tinkering with electronics.
"""

[[people]]
name = "Thor Wikfeldt"
organization = "PDC Center for High Performance Computing; CR staff"
photo = "thor_wikfeldt.jpg"
text = """
Application expert at the PDC Center for HPC in Stockholm with a background in
chemical physics.  Enjoys teaching, working at the interface between HPC and
academic research and interacting with talented scientists during CodeRefinery
workshops.
"""

[[people]]
name = "Jarno Rantaharju"
organization = "Aalto University, Finland"
photo = "jarno_rantaharju.jpg"
text = """
Research software engineer with background in physics and HPC.  Sees software
skills as increasingly necessary in research and life in general.  Enjoys
teaching and talking with researchers in different fields.
"""
