name: Build website

env:
  ZOLA_VERSION: "0.13.0"
  MAIN_BRANCH: "main"
  TARGET_BRANCH: "gh-pages"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install zola
      run: |
        set -x
        wget -O - \
           "https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin
    - name: Generate HTML
      run: zola build
    - name: Commit and push to target branch
      if: github.ref == 'refs/heads/{{ env.MAIN_BRANCH }}'
      run: |-
        git config --global user.email "workflow-bot@example.com"
        git config --global user.name "workflow-bot"
        git checkout --orphan $TARGET_BRANCH
        git rm --cached -r .
        mv public CNAME ..
        rm -rf *
        mv ../public/* .
        mv ../CNAME .
        touch .nojekyll
        git add .
        git commit -m "generated using zola build"
        git push --set-upstream origin $TARGET_BRANCH --force
